name: todo_UASMDI
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  google_sign_in: ^6.1.5
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.0
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
