// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHlZn1PDjdm6US0EA-hUuMguOcHvPlqe0',
    appId: '1:412284827472:web:88864472ed74ba6deb5e55',
    messagingSenderId: '412284827472',
    projectId: 'todo-uasmdi-925d2',
    authDomain: 'todo-uasmdi-925d2.firebaseapp.com',
    storageBucket: 'todo-uasmdi-925d2.firebasestorage.app',
    measurementId: 'G-4ZD0PWLL4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jfnbkShiQV8TYcBg-04iBWGevDW2W7Q',
    appId: '1:412284827472:android:0e4f4735fdc954c9eb5e55',
    messagingSenderId: '412284827472',
    projectId: 'todo-uasmdi-925d2',
    storageBucket: 'todo-uasmdi-925d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ACChZs1d5qyzoQPacRmjbAwLnjRHiOA',
    appId: '1:412284827472:ios:d150775d62d732b8eb5e55',
    messagingSenderId: '412284827472',
    projectId: 'todo-uasmdi-925d2',
    storageBucket: 'todo-uasmdi-925d2.firebasestorage.app',
    iosBundleId: 'com.example.todoFizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ACChZs1d5qyzoQPacRmjbAwLnjRHiOA',
    appId: '1:412284827472:ios:d150775d62d732b8eb5e55',
    messagingSenderId: '412284827472',
    projectId: 'todo-uasmdi-925d2',
    storageBucket: 'todo-uasmdi-925d2.firebasestorage.app',
    iosBundleId: 'com.example.todoFizard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHlZn1PDjdm6US0EA-hUuMguOcHvPlqe0',
    appId: '1:412284827472:web:43bd8fbce2d9e65feb5e55',
    messagingSenderId: '412284827472',
    projectId: 'todo-uasmdi-925d2',
    authDomain: 'todo-uasmdi-925d2.firebaseapp.com',
    storageBucket: 'todo-uasmdi-925d2.firebasestorage.app',
    measurementId: 'G-89QVBBVM1H',
  );

}